## 1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of pre-written code that provides functionality and modules which can be used and reused by developers to perform various tasks without having to write code from scratch. Libraries are designed to simplify and streamline the development process by providing ready-to-use functions, classes, and methods.

Why Do We Use Python Libraries?
Efficiency: Libraries save time by allowing developers to use pre-written, tested, and optimized code. This way, developers can focus on the core logic of their applications rather than reinventing the wheel.

Reusability: Libraries promote code reuse. Instead of writing the same code multiple times for different projects, developers can use libraries to achieve the same functionality.

Complexity Management: Libraries abstract complex operations into simple functions. For example, handling complex mathematical computations, data manipulation, or web development tasks becomes straightforward with the appropriate libraries.

Community Support: Popular libraries are maintained by the community, ensuring they are regularly updated, debugged, and optimized. This provides a reliable and robust foundation for building applications.

Standardization: Using widely-adopted libraries helps maintain consistency in coding practices across different projects and teams, making the codebase easier to understand and maintain.


## 2. What is the difference between Numpy array and List?

Key Differences Between NumPy Arrays and Python Lists
Data Type Homogeneity:

NumPy Array: All elements must be of the same type.
Python List: Can contain elements of different types.
Performance:

NumPy Array: Faster due to optimized C implementation and contiguous memory allocation.
Python List: Slower for numerical operations due to type-checking and general-purpose design.
Functionality:

NumPy Array: Supports advanced mathematical operations and broadcasting.
Python List: Flexible for general use but lacks specialized numerical functions.
Memory Efficiency:

NumPy Array: More efficient due to uniform data types and better memory management.
Python List: Less efficient, higher memory overhead due to heterogeneous elements.
Operations and Methods:

NumPy Array: Provides vectorized operations and complex mathematical functions.
Python List: Basic operations, suitable for diverse types of elements but requires loops for numerical computations.

In [1]:
# examples for numpy array
import numpy as np
arr = np.array([1, 2, 3, 4])
arr2 = arr * 2                    #Output:array([2, 4, 6, 8])
mean_value = np.mean(arr)          #Output:2.5

In [2]:
# examples for  python list
lst = [1, 2, 3, 4]
lst2 = [x * 2 for x in lst]  # Output: [2, 4, 6, 8]
mean_value = sum(lst) / len(lst)  # Output: 2.5

## 3. Find the shape, size and dimension of the following array?
## [[1, 2, 3, 4]
## [5, 6, 7, 8],
## [9, 10, 11, 12]]

In [3]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

shape = arr.shape  # Output: (3, 4)
print(shape)
size = arr.size  # Output: 12
print(size)
dimension = arr.ndim  # Output: 2
print(dimension)

(3, 4)
12
2


## 4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# to access the first row
first_row = arr[0]

print(first_row)

[1 2 3 4]


## 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [5]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
# to access the element at the third row and fourth column
element = arr[2, 3]
print(element)

12


## 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# flatten the array
flat_arr = arr.flatten()

# extract elements at odd indices
odd_indexed_elements = flat_arr[1::2]
print(odd_indexed_elements)

[ 2  4  6  8 10 12]


## 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [7]:
import numpy as np
#to generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.46018772 0.24552352 0.6314728 ]
 [0.23598057 0.32936153 0.11323272]
 [0.95623574 0.83900741 0.35864441]]


## 8. Describe the difference between np.random.rand and np.random.randn?

The functions np.random.rand and np.random.randn in NumPy are used to generate arrays of random numbers, but they differ in the distribution of the generated numbers:

np.random.rand
Distribution: Generates random numbers from a uniform distribution over the interval 
[
0
,
1
)
[0,1).
Syntax: np.random.rand(d0, d1, ..., dn)
Parameters: Accepts any number of dimensions (d0, d1, ..., dn) as arguments, and returns an array of the given shape filled with random samples from a uniform distribution.



In [8]:
import numpy as np
uniform_array = np.random.rand(3, 3)
print(uniform_array)

[[0.42343302 0.31110411 0.56743157]
 [0.36997119 0.21785568 0.87657328]
 [0.63313408 0.7531126  0.75780764]]


np.random.randn
Distribution: Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).
Syntax: np.random.randn(d0, d1, ..., dn)
Parameters: Accepts any number of dimensions (d0, d1, ..., dn) as arguments, and returns an array of the given shape filled with random samples from a standard normal distribution.

In [9]:
import numpy as np
normal_array = np.random.randn(3, 3)
print(normal_array)

[[ 0.85979888 -0.74519894 -0.57659364]
 [ 0.87580499  0.10188109 -0.86414104]
 [-0.0105752   0.94711735 -0.2609847 ]]


## 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

To increase the dimension of the given array, you can use the np.newaxis attribute or the np.expand_dims() function in NumPy. 
here's how you can do it:

Using np.newaxis

In [10]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# to increase dimension using np.newaxis
new_arr = arr[:, :, np.newaxis]

print(new_arr.shape)
print(new_arr)

(3, 4, 1)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [11]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# to increase dimension using np.expand_dims()
new_arr = np.expand_dims(arr, axis=2)
print(new_arr.shape)
print(new_arr)

(3, 4, 1)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


## 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [12]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Transpose the array using the .T attribute
transposed_arr = arr.T
print(transposed_arr)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## 11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrixes
4. Subtract matrix B from A 
5. Divide Matrix B by A

In [13]:
import numpy as np

# Define matrices A2 and B2
A = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# Perform addition using element-wise addition
addition_result = A + B

# Perform matrix multiplication
matrix_multiplication_result = np.matmul(A, B.T)  # Transpose of B to make the multiplication compatible

# Perform subtraction using element-wise subtraction
subtraction_result = A - B

# Perform element-wise division of B by A
division_result = B / A

# Print results
print("Addition Result:")
print(addition_result)
print("\nMatrix Multiplication Result:")
print(matrix_multiplication_result)
print("\nSubtraction Result:")
print(subtraction_result)
print("\nDivision Result (B by A):")
print(division_result)

Addition Result:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix Multiplication Result:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Subtraction Result:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division Result (B by A):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 12. Which function in Numpy can be used to swap the byte order of an array?

In NumPy, the function np.ndarray.byteswap() can be used to swap the byte order of an array.

In [14]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order of the array
arr.byteswap(inplace=True)

print(arr)

[16777216 33554432 50331648 67108864]


## 13. What is the significance of the np.linalg.inv function?

Significance of np.linalg.inv:

Solving Linear Systems: One of the most significant uses of matrix inversion is in solving systems of linear equations. Given a system Ax=b, where  A is a square matrix, x is a column vector of variables,and b is a column vector of constants

Computing Determinants: The determinant of a matrix is a fundamental quantity in linear algebra. The determinant of a matrix 
A is denoted as ∣A∣. The determinant is related to the matrix's invertibility; specifically, a matrix is invertible if and only if its determinant is nonzero.

Eigenvalue and Eigenvector Computations: In some cases, the inverse of a matrix is required to compute eigenvalues and eigenvectors of a square matrix 
𝐴 The eigenvectors of A are the vectors that do not change direction when multiplied by A, and the eigenvalues are the corresponding scaling factors.

## 14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to rearrange the elements of an array into a new shape while maintaining the same underlying data.

In [15]:
import numpy as np

# create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# reshape the array to a 2x3 matrix
reshaped_arr = np.reshape(arr, (2, 3))

print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


## 15. What is broadcasting in Numpy?

Broadcasting in NumPy is a mechanism that allows arrays with different shapes to be combined in arithmetic operations. When performing operations on arrays, NumPy compares their shapes element-wise. If the shapes are compatible, NumPy automatically adjusts the shapes of the arrays to make the operation possible. This adjustment, or "broadcasting", enables you to write cleaner and more concise code by avoiding the need to manually reshape or tile arrays to match each other's shapes.

In [16]:
import numpy as np

# Define two arrays with different shapes
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

# Add the arrays together
result = a + b

print(result)

[[11 22 33]
 [14 25 36]]
