## 1. What is a Python library? Why do we use Python libraries?

## 2. What is the difference between Numpy array and List?

In [2]:
# examples for numpy array
import numpy as np
arr = np.array([1, 2, 3, 4])
arr2 = arr * 2                    #Output:array([2, 4, 6, 8])
mean_value = np.mean(arr)          #Output:2.5

In [3]:
# examples for  python list
lst = [1, 2, 3, 4]
lst2 = [x * 2 for x in lst]  # Output: [2, 4, 6, 8]
mean_value = sum(lst) / len(lst)  # Output: 2.5

## 3. Find the shape, size and dimension of the following array?
## [[1, 2, 3, 4]
## [5, 6, 7, 8],
## [9, 10, 11, 12]]

In [9]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

shape = arr.shape  # Output: (3, 4)
print(shape)
size = arr.size  # Output: 12
print(size)
dimension = arr.ndim  # Output: 2
print(dimension)

(3, 4)
12
2


## 4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [10]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# to access the first row
first_row = arr[0]

print(first_row)

[1 2 3 4]


## 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [11]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
# to access the element at the third row and fourth column
element = arr[2, 3]
print(element)

12


## 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [12]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# flatten the array
flat_arr = arr.flatten()

# extract elements at odd indices
odd_indexed_elements = flat_arr[1::2]
print(odd_indexed_elements)

[ 2  4  6  8 10 12]


## 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [13]:
import numpy as np
#to generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.01899301 0.20935307 0.71574775]
 [0.26922896 0.35271773 0.90735445]
 [0.02637314 0.53727042 0.14745858]]


## 8. Describe the difference between np.random.rand and np.random.randn?

In [14]:
import numpy as np
uniform_array = np.random.rand(3, 3)
print(uniform_array)

[[0.96050551 0.86996279 0.31410903]
 [0.68871869 0.96770742 0.92037628]
 [0.21440908 0.84671242 0.9077447 ]]


In [15]:
import numpy as np
normal_array = np.random.randn(3, 3)
print(normal_array)

[[-0.28709829  2.70074615 -1.83054635]
 [-0.1473066  -0.41129757 -0.73389586]
 [-0.52548267 -1.21965743 -1.05770318]]


## 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [18]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# to increase dimension using np.newaxis
new_arr = arr[:, :, np.newaxis]

print(new_arr.shape)
print(new_arr)

(3, 4, 1)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [19]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# to increase dimension using np.expand_dims()
new_arr = np.expand_dims(arr, axis=2)
print(new_arr.shape)
print(new_arr)

(3, 4, 1)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


## 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [20]:
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Transpose the array using the .T attribute
transposed_arr = arr.T
print(transposed_arr)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## 11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1
1. Index wise multiplication
2. Matrix multiplication
3. Add both the matrixes
4. Subtract matrix B from A 
5. Divide Matrix B by A

In [22]:
import numpy as np

# Define matrices A2 and B2
A = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

# Perform addition using element-wise addition
addition_result = A + B

# Perform matrix multiplication
matrix_multiplication_result = np.matmul(A, B.T)  # Transpose of B to make the multiplication compatible

# Perform subtraction using element-wise subtraction
subtraction_result = A - B

# Perform element-wise division of B by A
division_result = B / A

# Print results
print("Addition Result:")
print(addition_result)
print("\nMatrix Multiplication Result:")
print(matrix_multiplication_result)
print("\nSubtraction Result:")
print(subtraction_result)
print("\nDivision Result (B by A):")
print(division_result)

Addition Result:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix Multiplication Result:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Subtraction Result:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division Result (B by A):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 12. Which function in Numpy can be used to swap the byte order of an array?

In [24]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order of the array
arr.byteswap(inplace=True)

print(arr)

[16777216 33554432 50331648 67108864]


## 13. What is the significance of the np.linalg.inv function?

## 14. What does the np.reshape function do, and how is it used?

In [25]:
import numpy as np

# create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# reshape the array to a 2x3 matrix
reshaped_arr = np.reshape(arr, (2, 3))

print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


## 15. What is broadcasting in Numpy?

In [26]:
import numpy as np

# Define two arrays with different shapes
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

# Add the arrays together
result = a + b

print(result)

[[11 22 33]
 [14 25 36]]
